import type { Metadata } from "next"
import { cookies } from "next/headers"

import { lora, spaceGrotesk, inter } from "../lib/fonts"
import "../assets/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

import { SidebarProvider, AppSidebar, SidebarTrigger } from "../components/sidebar/_index"
import { ThemeProvider } from "../components/theme-provider"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"

  return (
    <html lang="en" className={[lora.variable, spaceGrotesk.variable, inter.variable].join(" ")}>
      <body className="w-full bg-gray-100 p-4 font-inter text-gray-900 antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
