import "../assets/globals.css"

import type { Metadata } from "next"
import { lora, spaceGrotesk, inter } from "../lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={[lora.variable, spaceGrotesk.variable, inter.variable].join(" ")}>
      <body className="font-lora antialiased">{children}</body>
    </html>
  )
}
